resource "local_file" "localFile1" {
  filename = var.filename
  file_permission = 0744
  content = var.content
}

resource "local_file" "localFile2" {
  filename = "/Users/manoj/Git/terraform-learning/resources/file2.txt"
  content = var.customizedContent.content1
}

resource "local_file" "pet" {
  filename = "/Users/manoj/Git/terraform-learning/resources/pets.txt"
  content = "My favourite Pet is ${random_pet.pet-name.id} "
}

resource "random_pet" "pet-name" {
  prefix = "Mrs"
  separator = "."
  length = 4
}

output "pet-name" {
  value = random_pet.pet-name.id
  description = "record the value of pet id generated by random_pet resource"
}